sudo: required
dist: trusty
language: python
python:
- '3.5'
addons:
  postgresql: '9.4'
  apt:
    packages:
    - postgresql-9.4-postgis-2.1
before_install:
- export BOTO_CONFIG=/tmp/nowhere
- export DEBIAN_FRONTEND=noninteractive
- sudo add-apt-repository ppa:ubuntugis/ppa -y
- sudo -E apt-get -yq update &>> ~/apt-get-update.log
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install
  postgresql-9.4-postgis-2.2 squid3
- sudo apt-get -yq install libgdal1-dev
- gdal-config --version
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
  sed "s|::|:|g")
- export C_INCLUDE_PATH=/usr/include/gdal
- export CPLUS_INCLUDE_PATH=/usr/include/gdal
install:
- pip install mkwheelhouse==1.1.1
script:
- mkwheelhouse cadasta-wheelhouse -r cadasta-platform/requirements/dev.txt
notifications:
  slack:
    on_success: always
    on_failure: change
    secure: feHcuDtPoJ6M8C9wpQAu2nnuI98OhMZJLcPu/IgXC2GeFXHPybRzKdLvZJkDCxJZWCwqEt0DsJG/wk/Yh/jYQ/rORT6I5lYab6DvnFULl1c4C5tl7wdCEnXdwKUi3D1jxbN/FDa00GT0LEtNHaF9C08cgvalZ0WgQmVzw5gjnU7WTqqjSPVmP8Tf8Lknqwpy+v3SC5uRGn4/pr3sydfyUwg8b6DIvkKdNUDf5FsjBhjMpFcT2WERc+e34KkMMhY3/XhRW6fGjFzrkP+qyZj0Xr9B+Uuk4rzxzdwIS+E3BJ8HiPbP8AFzSVOm08YeA7cj/mleR9bY85dWH+qzmwXLhF6p7MyeRyFT2zxEajq/3PdNyi4c6im1zNFOKs+vchEQpqD0OWg2CBGeMPX9zBAgurdc6feLL6bazVzjm/Q+Xlob0QXgxWIOwhPDcGpGMbFdEonZN1POrBGQhZpXCUDVZsV9EwTmT8mNMRczsccIHlF8OxnTnMIaqIzOs2xs/TIqOz/PWIXP6R2eZEvNyY5KGFz/Eb1AJ5ayUy6bdQJeL+UTq7W376XKcP0BkSzBWaAYm1fTBtKAeiJ3owQg+z2UiagIM1EMiQBXp2NSMFqAZHUOXl0POr6K+cj9Iys/6WkBd5FvjZw63GpgY7urin6H7jfsqv1Qq28JmXD4HxfvKSY=
env:
  global:
  - secure: QsVyh075Ub93XEJ8PNp0v9LAxf0A4GZZZphJ3QqIc/uNfHQOBme/i8t47odfeRufz3XMLcvwcZVfW5BnSwkub07ctIWi+ZLrdDpKEhPtLwGac59lXl+tBlCj3qFoXKiQATpMlDqC7DI5LEMkyH3HGxQe3v5fN/e/MnWaH1C5Ng3bkYU6CohH20nkpHltzfvU4MQH2wvVQHVwdWdnP3p2i3byQhjckLsSB28Rk7q6frWOXNID4jTLbdA7fQiwLeGEFZylKlafsvG+17z53SLm4DjyI2+bwxxWsw9WN3C4mN8ase4NZ5+FVw9+/QojnPpoy/0o68Piau0k0MWMxJWvZ3CMtMoHbkVcyynsz/68GyTUp7uRpH890fgwqEXl46UXGZQNVOQnNTHqABe8ip4CHCnkL4SZJN6P+Wj67klGkwyNBiG/oizDQ/CktIRW4IqazK/e5cLkzyKR2jtvLXQ7RkmRqM89T+fVwRbr7h0+Sc8FUHlVOO/b6erL5lt7spYaz6JhpwJGcDIjhdlTThhlJz1P6giXioGrP26JIJoh2vPST/GyxsTWUGQBSJ2M/jcUlExCbQkZmDzC2u4DRpcz8i7Tyj+vQv2M506HX07BLWvHlqCu/yTCbVzuHORVKln9Ibg6AcaVbdT+DwpWroKn7ctkYilUe46QTyemUL4Dzkg=
  - secure: vjtAcaZHy6VCHHiG2w8GeIl851ebJmI8xiL4g4wPClwnfqmTEoMIhwXQyZUuluWzTWEoauCCih1b5PeQ7m46F4zrZKZf/xu0bce7fELa+3YZu6CcpDVxGiZjMcBFVtv71ccP/oBiOqSljs3knhpjPmkHnYE/AU5T6EkGtnyOr7n3OoZLMo/vGw2pkKxyrGuFUbDJeBNfMMVq67CdGWvoVRUzcLsihS2SWjagyAhNEcFarkc2vYe36mQuulAbdKPENjCNhj493KYGrnu9Yy0IKbQx5uegFq4k1jVnpiFTohWPhLsOmPi+7PHZEUKXFFl71ys5zM+6N3MEBHAJ52loNN3FWsY7xZKHetDKdwHwZN1xkkPeG8HehHdjpN8A9FBW7UPB2MK03gg2DIc8tY++WDuWORJvBcUpV3xeoA7Toh6Z1vCIu6/jvQY3uuEWgLojQ9brbA1fzDSa95+t1IKw+WYBIseWHw4Svi6xSd7vGGVqhocCbzr1IcQb7S8XMNObqg9d1xZ4Phz/WFj96fs4QduvFxsmBmi52LrP85xwYR2w+zrjs8XYReTrgoo9eiy3vWJTMHe6ILo3jH1+D/ehMRlrbxGhamq/pMXkO+R3WSffrClrAdyHIEq4RH+wkBTAWu0Qe6f7TMwYGxvRsCFdu2XGFDSs1SLIlvZ3a3UO6QQ=
